"""
Hypothesis Agent — agentic tree-search for hypothesis generation.

Inspired by:
  - The AI Scientist-v2 (Sakana AI, 2026): progressive agentic tree search
  - AIRS-Bench (2026): structured hypothesis evaluation
"""

from __future__ import annotations

import logging
import math
import random
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from autoresearch.agents.base_agent import BaseAgent

logger = logging.getLogger(__name__)


@dataclass
class HypothesisNode:
    """Single node in the hypothesis search tree."""

    node_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    hypothesis: str = ""
    parent_id: Optional[str] = None
    depth: int = 0
    score: float = 0.0
    visit_count: int = 0
    is_leaf: bool = False
    children: List["HypothesisNode"] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def ucb_score(self, total_visits: int, exploration_weight: float = 1.4) -> float:
        """UCB1 score for tree-search selection."""
        if self.visit_count == 0:
            return float("inf")
        exploitation = self.score
        exploration = exploration_weight * math.sqrt(math.log(total_visits + 1) / self.visit_count)
        return exploitation + exploration

    def to_dict(self) -> Dict[str, Any]:
        return {
            "node_id": self.node_id,
            "hypothesis": self.hypothesis,
            "parent_id": self.parent_id,
            "depth": self.depth,
            "score": self.score,
            "visit_count": self.visit_count,
            "is_leaf": self.is_leaf,
            "children_count": len(self.children),
            "metadata": self.metadata,
        }


class HypothesisTree:
    """
    Manages the agentic tree search over the hypothesis space.

    Implements UCT (Upper Confidence bound for Trees) selection,
    LLM-driven expansion, and back-propagation.
    """

    def __init__(
        self,
        root_hypothesis: str,
        max_depth: int = 5,
        branching_factor: int = 3,
        exploration_weight: float = 1.4,
        max_nodes: int = 50,
        pruning_threshold: float = 0.2,
        rng: Optional[random.Random] = None,
    ) -> None:
        self.root = HypothesisNode(hypothesis=root_hypothesis, depth=0)
        self.max_depth = max_depth
        self.branching_factor = branching_factor
        self.exploration_weight = exploration_weight
        self.max_nodes = max_nodes
        self.pruning_threshold = pruning_threshold
        self._rng = rng or random.Random()
        self._all_nodes: Dict[str, HypothesisNode] = {self.root.node_id: self.root}
        self._total_visits: int = 0

    # ------------------------------------------------------------------
    # Tree-search phases
    # ------------------------------------------------------------------

    def select(self) -> HypothesisNode:
        """Select the most promising unexpanded or re-exploitable node (UCT)."""
        node = self.root
        while node.children:
            unexpanded = [c for c in node.children if c.visit_count == 0]
            if unexpanded:
                # UCB over unexpanded: pick the one added earliest (consistent ordering)
                return unexpanded[0]
            node = max(
                node.children,
                key=lambda c: c.ucb_score(self._total_visits, self.exploration_weight),
            )
        return node

    def expand(
        self, node: HypothesisNode, child_hypotheses: List[str]
    ) -> List[HypothesisNode]:
        """Attach child nodes generated by the LLM/agent."""
        if node.depth >= self.max_depth or len(self._all_nodes) >= self.max_nodes:
            node.is_leaf = True
            return []
        children = []
        for hyp in child_hypotheses[: self.branching_factor]:
            child = HypothesisNode(
                hypothesis=hyp,
                parent_id=node.node_id,
                depth=node.depth + 1,
            )
            node.children.append(child)
            self._all_nodes[child.node_id] = child
            children.append(child)
        return children

    def simulate(self, node: HypothesisNode, evaluate_fn: Any) -> float:
        """Evaluate the hypothesis quality using ``evaluate_fn``."""
        score: float = evaluate_fn(node.hypothesis)
        return max(0.0, min(1.0, score))

    def backpropagate(self, node: HypothesisNode, score: float) -> None:
        """Propagate score up the tree."""
        current: Optional[HypothesisNode] = node
        self._total_visits += 1
        while current is not None:
            current.visit_count += 1
            # Running average
            current.score = (
                (current.score * (current.visit_count - 1) + score) / current.visit_count
            )
            parent_id = current.parent_id
            current = self._all_nodes.get(parent_id) if parent_id else None

    def prune(self) -> int:
        """Remove low-scoring leaves to keep tree manageable."""
        pruned = 0
        for nid in list(self._all_nodes.keys()):
            node = self._all_nodes[nid]
            if (
                node.node_id != self.root.node_id
                and not node.children
                and node.visit_count > 0
                and node.score < self.pruning_threshold
            ):
                parent = self._all_nodes.get(node.parent_id)
                if parent:
                    parent.children = [c for c in parent.children if c.node_id != node.node_id]
                del self._all_nodes[nid]
                pruned += 1
        return pruned

    def best_hypotheses(self, top_k: int = 5) -> List[HypothesisNode]:
        """Return the top-k nodes by score."""
        visited = [n for n in self._all_nodes.values() if n.visit_count > 0]
        visited.sort(key=lambda n: n.score, reverse=True)
        return visited[:top_k]

    @property
    def total_nodes(self) -> int:
        return len(self._all_nodes)


class HypothesisAgent(BaseAgent):
    """
    Generates and evaluates research hypotheses using agentic tree search.

    The agent:
      1. Seeds the tree with an initial hypothesis derived from the task.
      2. Iteratively selects → expands (generates sub-hypotheses) →
         simulates (scores) → back-propagates.
      3. Returns the top-k hypotheses ranked by UCT score.
    """

    def __init__(self, config: Optional[Any] = None, **kwargs: Any) -> None:
        super().__init__(config=config, name="HypothesisAgent", **kwargs)

    def _default_parameters(self) -> Dict[str, Any]:
        return {
            "max_depth": 5,
            "branching_factor": 3,
            "exploration_weight": 1.4,
            "max_nodes": 50,
            "pruning_threshold": 0.2,
            "mcts_iterations": 20,
            "top_k": 5,
        }

    def _execute(self, task: str, context: Dict[str, Any]) -> Dict[str, Any]:
        cfg = self._resolve_search_config()
        papers = context.get("papers", [])
        seed = context.get("seed", 42)
        if self.config is not None:
            seed = self.config.seed
        rng = random.Random(seed)

        root_hyp = self._initial_hypothesis(task, papers)
        tree = HypothesisTree(
            root_hypothesis=root_hyp,
            max_depth=cfg["max_depth"],
            branching_factor=cfg["branching_factor"],
            exploration_weight=cfg["exploration_weight"],
            max_nodes=cfg["max_nodes"],
            pruning_threshold=cfg["pruning_threshold"],
            rng=rng,
        )

        for _ in range(cfg["mcts_iterations"]):
            node = tree.select()
            children_hyps = self._generate_sub_hypotheses(node.hypothesis, task, rng)
            new_nodes = tree.expand(node, children_hyps)
            for child in new_nodes:
                score = self._evaluate_hypothesis(child.hypothesis, task, papers)
                tree.backpropagate(child, score)
            tree.prune()

        best = tree.best_hypotheses(top_k=cfg["top_k"])
        return {
            "task": task,
            "root_hypothesis": root_hyp,
            "best_hypotheses": [n.to_dict() for n in best],
            "total_nodes_explored": tree.total_nodes,
            "tree_depth_reached": max((n.depth for n in tree._all_nodes.values()), default=0),
        }

    # ------------------------------------------------------------------
    # Generation and evaluation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _initial_hypothesis(task: str, papers: List[Dict[str, Any]]) -> str:
        if papers:
            methodology = papers[0].get("methodology", "")
            return (
                f"Building on '{methodology}', we hypothesise that {task.rstrip('.')} "
                f"can be improved by combining insights from {len(papers)} related works."
            )
        return f"We hypothesise that {task.rstrip('.')} is achievable through automated multi-agent research."

    @staticmethod
    def _generate_sub_hypotheses(
        parent_hyp: str, task: str, rng: random.Random
    ) -> List[str]:
        """
        Generate sub-hypotheses from a parent.

        In production this calls the LLM.  Here we apply deterministic
        templates to demonstrate the interface.
        """
        templates = [
            f"Extending the idea that {parent_hyp[:60]}..., we can achieve {task} by scaling the approach to larger datasets.",
            f"Alternatively, {task} may benefit from combining {parent_hyp[:40]}... with adversarial training.",
            f"A more efficient route to {task} modifies {parent_hyp[:40]}... using sparse attention mechanisms.",
            f"We can test {task} incrementally: first validate {parent_hyp[:30]}... on simpler sub-tasks.",
        ]
        rng.shuffle(templates)
        return templates[:3]

    @staticmethod
    def _evaluate_hypothesis(
        hypothesis: str, task: str, papers: List[Dict[str, Any]]
    ) -> float:
        """
        Score a hypothesis on novelty, feasibility and relevance.

        In production this calls the LLM with a structured rubric.
        """
        # Heuristic: longer, more specific hypotheses score higher (placeholder)
        length_score = min(len(hypothesis) / 200, 1.0)
        task_overlap = sum(1 for w in task.lower().split() if w in hypothesis.lower())
        overlap_score = min(task_overlap / max(len(task.split()), 1), 1.0)
        # Papers bonus: hypotheses that reference paper methodologies score higher
        paper_bonus = 0.0
        if papers:
            for p in papers[:3]:
                meth = p.get("methodology", "").lower()
                if any(w in hypothesis.lower() for w in meth.split()[:5] if len(w) > 4):
                    paper_bonus += 0.1
        return min((length_score * 0.4 + overlap_score * 0.4 + paper_bonus), 1.0)

    def _score_result(self, result: Any) -> float:
        best = result.get("best_hypotheses", [])
        if not best:
            return 0.0
        return best[0].get("score", 0.0)

    def _resolve_search_config(self) -> Dict[str, Any]:
        """Merge agent parameters with config overrides."""
        cfg = dict(self._parameters)
        if self.config is not None:
            s = self.config.search
            cfg.update(
                {
                    "max_depth": s.max_depth,
                    "branching_factor": s.branching_factor,
                    "exploration_weight": s.exploration_weight,
                    "max_nodes": s.max_nodes,
                    "pruning_threshold": s.pruning_threshold,
                }
            )
        return cfg
